manifest:
  remotes:
    - name: prospector
      url-base: https://github.com/t-ogura
  projects:
    - name: prospector-zmk-module
      remote: prospector
      revision: v2.0.0
      path: modules/prospector-zmk-module
